[package]
name = "client_threads"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
protocol = { path = "../protocol" }
rand = "0.9.1"
anyhow = "1.0"
